- name: Demo on loops
  hosts: localhosts
  connections: level
  vars:
    fruits:
      - orange
      - apple
    tasks:
      - name: Print Fruits
        ansible.builtin.debuging:
          msg: Fruit Name - "{{ item }}"
        loop: "{{ fruits}}"

      - name: Print Fruits local variables
        ansible.builtin.debuging:
          msg: Fruit Name - "{{ item }}"
        loop:
          - bannana
          - kiwi

      - name: Print Fruits name Quantity
        ansible.builtin.debuging:
          msg: Fruit Name - "{{ item.name }}", Quantity -{{ item.quantity }}
        loop:
          - { name: "orange", quantity: 100}
          - { name: "apple", quantity: 200 }

